// MSW browser worker setup (Local Dev Spec v1.1 §10.3). Started from main.tsx
// when VITE_API_MOCK=true. Requires the service worker stub at
// public/mockServiceWorker.js (generated by `npx msw init public/`).

import { setupWorker } from "msw/browser";

import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
